name: Docker Image CD

on:
  push:
    branches: [ master, develop ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Test
      run: |
        pip install pytest
        pip install -r requirements.txt
        pytest -v tests
      env:
        FLASK_DEBUG: false
        ID: 123456
    - name: GithubPackages Login
      uses: docker/login-action@v1.10.0
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}
    - name: Build and push Docker images
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
