name: Docker Image CD

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Test
      run: |
        pip install pytest
        pip install -r requirements.txt
        pytest -v tests
      env:
        FLASK_DEBUG: false
        ID: 123456
    
  deploy:
    needs: test
    uses: Geode-solutions/actions/.github/workflows/docker-build-squash-push.yml@master
    with:
      image_name: 'geode-backend'
      tag: ${{ github.ref_name }}
      args: --build-arg TOKEN= & ${{ secrets.TOKEN }}
    secrets: 
      TOKEN: ${{secrets.GITHUB_TOKEN}}

